import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { env } from "../config/env.js";

type PdfDoc = InstanceType<typeof PDFDocument>;
type ReportRow = { type: string; date: string; party: string; category: string; amount: number; status: string };

const blue = "#2563eb";
const dark = "#0f172a";
const muted = "#64748b";
const line = "#dbe3ef";

function money(value: number) {
  return `Rs. ${new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value || 0)}`;
}

function createDocument(title: string) {
  const doc = new PDFDocument({ size: "A4", margin: 42, bufferPages: true, info: { Title: title, Author: env.companyName, Creator: "EFMS" } });
  return doc;
}

function header(doc: PdfDoc, title: string, subtitle?: string) {
  doc.save().roundedRect(42, 35, 54, 54, 10).fill(blue).fillColor("white").font("Helvetica-Bold").fontSize(17).text("EFMS", 48, 54, { width: 42, align: "center" }).restore();
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(18).text(env.companyName, 110, 38, { width: 300 });
  doc.fillColor(muted).font("Helvetica").fontSize(8).text([env.companyAddress, env.companyGstin ? `GSTIN: ${env.companyGstin}` : "", env.companyEmail].filter(Boolean).join("  |  "), 110, 63, { width: 400 });
  doc.moveTo(42, 100).lineTo(553, 100).strokeColor(blue).lineWidth(2).stroke();
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(19).text(title, 42, 116);
  if (subtitle) doc.fillColor(muted).font("Helvetica").fontSize(9).text(subtitle, 42, 142);
  doc.y = subtitle ? 169 : 151;
}

function addPage(doc: PdfDoc, title: string, subtitle?: string) {
  doc.addPage();
  header(doc, title, subtitle);
}

function finish(doc: PdfDoc) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    doc.moveTo(42, 800).lineTo(553, 800).strokeColor(line).lineWidth(1).stroke();
    doc.fillColor(muted).font("Helvetica").fontSize(8).text(`Generated by EFMS on ${new Date().toLocaleString("en-IN")}`, 42, 809, { width: 350 });
    doc.text(`Page ${index + 1} of ${range.count}`, 430, 809, { width: 123, align: "right" });
  }
  doc.end();
}

function toBuffer(doc: PdfDoc) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function tableHeader(doc: PdfDoc, columns: Array<{ label: string; x: number; width: number; align?: "left" | "right" }>, y: number) {
  doc.save().roundedRect(42, y, 511, 24, 4).fill(dark).restore();
  columns.forEach((column) => doc.fillColor("white").font("Helvetica-Bold").fontSize(8).text(column.label, column.x, y + 8, { width: column.width, align: column.align }));
  return y + 28;
}

function detailLine(doc: PdfDoc, label: string, value: string, x: number, y: number, width = 220) {
  doc.fillColor(muted).font("Helvetica").fontSize(8).text(label.toUpperCase(), x, y, { width });
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(10).text(value || "-", x, y + 12, { width });
}

export async function generateReportPdf(input: { from: Date; to: Date; rows: ReportRow[]; income: number; expense: number }) {
  const title = "Financial Statement";
  const subtitle = `${input.from.toLocaleDateString("en-IN")} to ${input.to.toLocaleDateString("en-IN")}`;
  const doc = createDocument(title);
  const promise = toBuffer(doc);
  header(doc, title, subtitle);
  const cards = [
    { label: "TOTAL INCOME", value: input.income, color: "#16a34a" },
    { label: "TOTAL EXPENSE", value: input.expense, color: "#dc2626" },
    { label: "NET PROFIT / LOSS", value: input.income - input.expense, color: input.income - input.expense >= 0 ? "#2563eb" : "#dc2626" }
  ];
  const cardY = doc.y;
  cards.forEach((card, index) => {
    const x = 42 + index * 174;
    doc.save().roundedRect(x, cardY, 163, 58, 7).fill("#f8fafc").strokeColor(line).stroke().restore();
    doc.fillColor(muted).font("Helvetica-Bold").fontSize(7).text(card.label, x + 10, cardY + 11, { width: 143 });
    doc.fillColor(card.color).font("Helvetica-Bold").fontSize(13).text(money(card.value), x + 10, cardY + 29, { width: 143 });
  });
  doc.y = cardY + 78;
  const columns = [
    { label: "TYPE", x: 48, width: 54 }, { label: "DATE", x: 105, width: 61 }, { label: "PARTY", x: 169, width: 115 },
    { label: "CATEGORY / SOURCE", x: 287, width: 110 }, { label: "STATUS", x: 400, width: 65 }, { label: "AMOUNT", x: 468, width: 78, align: "right" as const }
  ];
  let y = tableHeader(doc, columns, doc.y);
  input.rows.forEach((row, index) => {
    if (y > 770) { addPage(doc, title, subtitle); y = tableHeader(doc, columns, doc.y); }
    if (index % 2 === 0) doc.save().rect(42, y - 3, 511, 25).fill("#f8fafc").restore();
    const values = [row.type, row.date, row.party, row.category, row.status, money(row.amount)];
    columns.forEach((column, columnIndex) => doc.fillColor(dark).font("Helvetica").fontSize(7.5).text(values[columnIndex], column.x, y + 5, { width: column.width, height: 13, ellipsis: true, align: column.align }));
    y += 25;
  });
  if (!input.rows.length) doc.fillColor(muted).fontSize(10).text("No transactions found for this period.", 42, y + 20, { width: 511, align: "center" });
  finish(doc);
  return promise;
}

export async function generateInvoicePdf(invoice: Record<string, any>) {
  const title = String(invoice.type || "invoice").replaceAll("_", " ").toUpperCase();
  const doc = createDocument(`${title} ${invoice.invoiceNumber}`);
  const promise = toBuffer(doc);
  header(doc, title, `Document No: ${invoice.invoiceNumber}`);
  detailLine(doc, "Customer", invoice.customer, 42, doc.y);
  detailLine(doc, "Customer GSTIN", invoice.customerGst || "N/A", 300, doc.y);
  doc.y += 44;
  const columns = [
    { label: "DESCRIPTION", x: 48, width: 220 }, { label: "QTY", x: 275, width: 42, align: "right" as const },
    { label: "RATE", x: 325, width: 75, align: "right" as const }, { label: "GST", x: 408, width: 44, align: "right" as const },
    { label: "TOTAL", x: 460, width: 86, align: "right" as const }
  ];
  let y = tableHeader(doc, columns, doc.y);
  for (const lineItem of invoice.lines ?? []) {
    if (y > 750) { addPage(doc, title, `Document No: ${invoice.invoiceNumber}`); y = tableHeader(doc, columns, doc.y); }
    const lineTotal = Number(lineItem.quantity) * Number(lineItem.unitPrice) * (1 + Number(lineItem.gstRate) / 100);
    const values = [lineItem.description, String(lineItem.quantity), money(lineItem.unitPrice), `${lineItem.gstRate}%`, money(lineTotal)];
    columns.forEach((column, index) => doc.fillColor(dark).font("Helvetica").fontSize(8).text(values[index], column.x, y + 5, { width: column.width, height: 28, ellipsis: true, align: column.align }));
    doc.moveTo(42, y + 31).lineTo(553, y + 31).strokeColor(line).stroke();
    y += 35;
  }
  y += 10;
  [["Subtotal", invoice.subtotal], ["GST", invoice.gstAmount], ["Grand Total", invoice.totalAmount]].forEach(([label, value], index) => {
    doc.fillColor(index === 2 ? blue : muted).font(index === 2 ? "Helvetica-Bold" : "Helvetica").fontSize(index === 2 ? 12 : 9).text(String(label), 375, y, { width: 85 });
    doc.text(money(Number(value)), 460, y, { width: 86, align: "right" }); y += index === 2 ? 24 : 18;
  });
  const qr = await QRCode.toBuffer(`${env.verifyBaseUrl}/verify/invoice/${invoice.invoiceNumber}`, { width: 140, margin: 1 });
  doc.image(qr, 42, Math.min(y + 8, 690), { width: 88 }).fillColor(muted).fontSize(7).text("Scan to verify", 42, Math.min(y + 100, 782), { width: 88, align: "center" });
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(9).text("Authorized Signatory", 400, Math.min(y + 82, 770), { width: 146, align: "center" });
  if (invoice.remarks) doc.fillColor(muted).font("Helvetica").fontSize(8).text(`Remarks: ${invoice.remarks}`, 150, Math.min(y + 20, 730), { width: 220 });
  finish(doc);
  return promise;
}

export async function generateVoucherPdf(voucher: Record<string, any>) {
  const title = `${String(voucher.type).toUpperCase()} VOUCHER`;
  const doc = createDocument(`${title} ${voucher.voucherNumber}`);
  const promise = toBuffer(doc);
  header(doc, title, `Voucher No: ${voucher.voucherNumber}`);
  const startY = doc.y;
  detailLine(doc, "Date", new Date(voucher.createdAt).toLocaleDateString("en-IN"), 42, startY);
  detailLine(doc, "Receiver", voucher.receiver || "-", 300, startY);
  detailLine(doc, "Purpose", voucher.purpose, 42, startY + 48, 500);
  detailLine(doc, "Payment Mode", voucher.paymentMode || "-", 42, startY + 96);
  detailLine(doc, "Reference", voucher.referenceNo || "-", 300, startY + 96);
  doc.save().roundedRect(42, startY + 145, 511, 68, 8).fill("#eff6ff").strokeColor("#bfdbfe").stroke().restore();
  doc.fillColor(muted).font("Helvetica-Bold").fontSize(8).text("AMOUNT", 58, startY + 161);
  doc.fillColor(blue).font("Helvetica-Bold").fontSize(22).text(money(voucher.amount), 58, startY + 178);
  const qr = await QRCode.toBuffer(`${env.verifyBaseUrl}/verify/voucher/${voucher.voucherNumber}`, { width: 140, margin: 1 });
  doc.image(qr, 42, startY + 245, { width: 95 }).fillColor(muted).fontSize(7).text("Scan to verify", 42, startY + 343, { width: 95, align: "center" });
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(9).text("Receiver Signature", 190, startY + 330, { width: 130, align: "center" });
  doc.text("Authorized Signatory", 400, startY + 330, { width: 145, align: "center" });
  doc.moveTo(190, startY + 325).lineTo(320, startY + 325).strokeColor(dark).stroke();
  doc.moveTo(400, startY + 325).lineTo(545, startY + 325).stroke();
  if (voucher.remarks) doc.fillColor(muted).font("Helvetica").fontSize(8).text(`Remarks: ${voucher.remarks}`, 42, startY + 390, { width: 500 });
  finish(doc);
  return promise;
}
