import PDFDocument from "pdfkit";
import QRCode from "qrcode";
import { env } from "../config/env.js";
import { existsSync } from "node:fs";
import path from "node:path";

type PdfDoc = InstanceType<typeof PDFDocument>;
type ReportRow = { type: string; date: string; party: string; category: string; amount: number; status: string };

const blue = "#2563eb";
const dark = "#0f172a";
const muted = "#64748b";
const line = "#dbe3ef";

function money(value: number) {
  return `Rs. ${new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value || 0)}`;
}

function createDocument(title: string) {
  const doc = new PDFDocument({ size: "A4", margin: 42, bufferPages: true, info: { Title: title, Author: env.companyName, Creator: "EFMS" } });
  return doc;
}

function companyName() {
  const normalized = env.companyName.trim().toLowerCase().replaceAll(".", "");
  return ["htech solution", "htech solution pvt ltd"].includes(normalized) ? "Htech Solutions Pvt. Ltd." : env.companyName;
}

function logoPath() {
  const candidates = [path.resolve(process.cwd(), "../image.png"), path.resolve(process.cwd(), "image.png")];
  return candidates.find((candidate) => existsSync(candidate));
}

function header(doc: PdfDoc, title: string, subtitle?: string, useCompanyLogo = false) {
  const logo = logoPath();
  if (logo) {
    doc.save().roundedRect(42, 35, 54, 54, 10).fill("white").strokeColor(line).stroke().restore();
    doc.image(logo, 46, 39, { fit: [46, 46], align: "center", valign: "center" });
  } else {
    doc.save().roundedRect(42, 35, 54, 54, 10).fill(blue).fillColor("white").font("Helvetica-Bold").fontSize(17).text("EFMS", 48, 54, { width: 42, align: "center" }).restore();
  }
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(18).text(companyName(), 110, 38, { width: 380 });
  doc.fillColor(muted).font("Helvetica").fontSize(8).text([env.companyAddress, env.companyGstin ? `GSTIN: ${env.companyGstin}` : "", env.companyEmail].filter(Boolean).join("  |  "), 110, 63, { width: 400 });
  doc.moveTo(42, 100).lineTo(553, 100).strokeColor(blue).lineWidth(2).stroke();
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(19).text(title, 42, 116);
  if (subtitle) doc.fillColor(muted).font("Helvetica").fontSize(9).text(subtitle, 42, 142);
  doc.y = subtitle ? 169 : 151;
}

function addPage(doc: PdfDoc, title: string, subtitle?: string) {
  doc.addPage();
  header(doc, title, subtitle);
}

function finish(doc: PdfDoc) {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    doc.page.margins.bottom = 0;
    doc.moveTo(42, 806).lineTo(553, 806).strokeColor(line).lineWidth(1).stroke();
    doc.fillColor(muted).font("Helvetica").fontSize(7).text(`Generated by EFMS on ${new Date().toLocaleString("en-IN")}`, 42, 814, { width: 350, lineBreak: false });
    doc.text(`Page ${index + 1} of ${range.count}`, 430, 814, { width: 123, align: "right", lineBreak: false });
  }
  doc.end();
}

function toBuffer(doc: PdfDoc) {
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

function tableHeader(doc: PdfDoc, columns: Array<{ label: string; x: number; width: number; align?: "left" | "right" }>, y: number) {
  doc.save().roundedRect(42, y, 511, 24, 4).fill(dark).restore();
  columns.forEach((column) => doc.fillColor("white").font("Helvetica-Bold").fontSize(8).text(column.label, column.x, y + 8, { width: column.width, align: column.align }));
  return y + 28;
}

function detailLine(doc: PdfDoc, label: string, value: string, x: number, y: number, width = 220) {
  doc.fillColor(muted).font("Helvetica").fontSize(8).text(label.toUpperCase(), x, y, { width });
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(10).text(value || "-", x, y + 12, { width });
}

export async function generateReportPdf(input: { from: Date; to: Date; rows: ReportRow[]; income: number; expense: number }) {
  const title = "Financial Statement";
  const subtitle = `${input.from.toLocaleDateString("en-IN")} to ${input.to.toLocaleDateString("en-IN")}`;
  const doc = createDocument(title);
  const promise = toBuffer(doc);
  header(doc, title, subtitle);
  const cards = [
    { label: "TOTAL INCOME", value: input.income, color: "#16a34a" },
    { label: "TOTAL EXPENSE", value: input.expense, color: "#dc2626" },
    { label: "NET PROFIT / LOSS", value: input.income - input.expense, color: input.income - input.expense >= 0 ? "#2563eb" : "#dc2626" }
  ];
  const cardY = doc.y;
  cards.forEach((card, index) => {
    const x = 42 + index * 174;
    doc.save().roundedRect(x, cardY, 163, 58, 7).fill("#f8fafc").strokeColor(line).stroke().restore();
    doc.fillColor(muted).font("Helvetica-Bold").fontSize(7).text(card.label, x + 10, cardY + 11, { width: 143 });
    doc.fillColor(card.color).font("Helvetica-Bold").fontSize(13).text(money(card.value), x + 10, cardY + 29, { width: 143 });
  });
  doc.y = cardY + 78;
  const columns = [
    { label: "TYPE", x: 48, width: 54 }, { label: "DATE", x: 105, width: 61 }, { label: "PARTY", x: 169, width: 115 },
    { label: "CATEGORY / SOURCE", x: 287, width: 110 }, { label: "STATUS", x: 400, width: 65 }, { label: "AMOUNT", x: 468, width: 78, align: "right" as const }
  ];
  let y = tableHeader(doc, columns, doc.y);
  input.rows.forEach((row, index) => {
    if (y > 770) { addPage(doc, title, subtitle); y = tableHeader(doc, columns, doc.y); }
    if (index % 2 === 0) doc.save().rect(42, y - 3, 511, 25).fill("#f8fafc").restore();
    const values = [row.type, row.date, row.party, row.category, row.status, money(row.amount)];
    columns.forEach((column, columnIndex) => doc.fillColor(dark).font("Helvetica").fontSize(7.5).text(values[columnIndex], column.x, y + 5, { width: column.width, height: 13, ellipsis: true, align: column.align }));
    y += 25;
  });
  if (!input.rows.length) doc.fillColor(muted).fontSize(10).text("No transactions found for this period.", 42, y + 20, { width: 511, align: "center" });
  finish(doc);
  return promise;
}

export async function generateInvoicePdf(invoice: Record<string, any>) {
  const title = String(invoice.type || "invoice").replaceAll("_", " ").toUpperCase();
  const doc = createDocument(`${title} ${invoice.invoiceNumber}`);
  const promise = toBuffer(doc);
  header(doc, title, `Document No: ${invoice.invoiceNumber}`);
  detailLine(doc, "Customer", invoice.customer, 42, doc.y);
  detailLine(doc, "Customer GSTIN", invoice.customerGst || "N/A", 300, doc.y);
  doc.y += 44;
  const columns = [
    { label: "DESCRIPTION", x: 48, width: 220 }, { label: "QTY", x: 275, width: 42, align: "right" as const },
    { label: "RATE", x: 325, width: 75, align: "right" as const }, { label: "GST", x: 408, width: 44, align: "right" as const },
    { label: "TOTAL", x: 460, width: 86, align: "right" as const }
  ];
  let y = tableHeader(doc, columns, doc.y);
  for (const lineItem of invoice.lines ?? []) {
    if (y > 750) { addPage(doc, title, `Document No: ${invoice.invoiceNumber}`); y = tableHeader(doc, columns, doc.y); }
    const lineTotal = Number(lineItem.quantity) * Number(lineItem.unitPrice) * (1 + Number(lineItem.gstRate) / 100);
    const values = [lineItem.description, String(lineItem.quantity), money(lineItem.unitPrice), `${lineItem.gstRate}%`, money(lineTotal)];
    columns.forEach((column, index) => doc.fillColor(dark).font("Helvetica").fontSize(8).text(values[index], column.x, y + 5, { width: column.width, height: 28, ellipsis: true, align: column.align }));
    doc.moveTo(42, y + 31).lineTo(553, y + 31).strokeColor(line).stroke();
    y += 35;
  }
  y += 10;
  [["Subtotal", invoice.subtotal], ["GST", invoice.gstAmount], ["Grand Total", invoice.totalAmount]].forEach(([label, value], index) => {
    doc.fillColor(index === 2 ? blue : muted).font(index === 2 ? "Helvetica-Bold" : "Helvetica").fontSize(index === 2 ? 12 : 9).text(String(label), 375, y, { width: 85 });
    doc.text(money(Number(value)), 460, y, { width: 86, align: "right" }); y += index === 2 ? 24 : 18;
  });
  const qr = await QRCode.toBuffer(`${env.verifyBaseUrl}/verify/invoice/${invoice.invoiceNumber}`, { width: 140, margin: 1 });
  doc.image(qr, 42, Math.min(y + 8, 690), { width: 88 }).fillColor(muted).fontSize(7).text("Scan to verify", 42, Math.min(y + 100, 782), { width: 88, align: "center" });
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(9).text("Authorized Signatory", 400, Math.min(y + 82, 770), { width: 146, align: "center" });
  if (invoice.remarks) doc.fillColor(muted).font("Helvetica").fontSize(8).text(`Remarks: ${invoice.remarks}`, 150, Math.min(y + 20, 730), { width: 220 });
  finish(doc);
  return promise;
}

export async function generateVoucherPdf(voucher: Record<string, any>) {
  const title = `${String(voucher.type).toUpperCase()} VOUCHER`;
  const doc = createDocument(`${title} ${voucher.voucherNumber}`);
  const promise = toBuffer(doc);
  const drawCopy = (top: number, copy: string) => {
    const logo = logoPath();
    doc.save().roundedRect(42, top, 511, 350, 8).strokeColor(line).lineWidth(1).stroke().restore();
    if (logo) doc.image(logo, 55, top + 14, { fit: [42, 42] });
    doc.fillColor(dark).font("Helvetica-Bold").fontSize(15).text(companyName(), 108, top + 14, { width: 300 });
    doc.fillColor(muted).font("Helvetica").fontSize(7).text([env.companyAddress, env.companyGstin ? `GSTIN: ${env.companyGstin}` : ""].filter(Boolean).join(" | "), 108, top + 36, { width: 330, height: 18 });
    doc.fillColor(blue).font("Helvetica-Bold").fontSize(8).text(copy.toUpperCase(), 443, top + 18, { width: 92, align: "right" });
    doc.moveTo(55, top + 66).lineTo(540, top + 66).strokeColor(blue).lineWidth(1.5).stroke();
    doc.fillColor(dark).font("Helvetica-Bold").fontSize(14).text(title, 55, top + 78);
    doc.fillColor(muted).font("Helvetica").fontSize(7).text(`Voucher No: ${voucher.voucherNumber}`, 390, top + 82, { width: 150, align: "right" });
    detailLine(doc, "Date", new Date(voucher.createdAt).toLocaleDateString("en-IN"), 55, top + 112, 120);
    detailLine(doc, "Receiver", voucher.receiver || "-", 205, top + 112, 180);
    detailLine(doc, "Payment Mode", String(voucher.paymentMode || "-").toUpperCase(), 410, top + 112, 125);
    detailLine(doc, "Purpose", voucher.purpose, 55, top + 158, 315);
    detailLine(doc, "Reference", voucher.referenceNo || "-", 410, top + 158, 125);
    doc.save().roundedRect(55, top + 206, 485, 52, 6).fill("#eff6ff").strokeColor("#bfdbfe").stroke().restore();
    doc.fillColor(muted).font("Helvetica-Bold").fontSize(7).text("AMOUNT PAID", 68, top + 218);
    doc.fillColor(blue).font("Helvetica-Bold").fontSize(18).text(money(voucher.amount), 68, top + 232);
    if (voucher.remarks) doc.fillColor(muted).font("Helvetica").fontSize(7).text(`Remarks: ${voucher.remarks}`, 55, top + 272, { width: 220, height: 22, ellipsis: true });
    doc.moveTo(300, top + 310).lineTo(400, top + 310).strokeColor(dark).stroke();
    doc.moveTo(435, top + 310).lineTo(535, top + 310).stroke();
    doc.fillColor(dark).font("Helvetica-Bold").fontSize(7).text("Receiver Signature", 300, top + 317, { width: 100, align: "center" });
    doc.text("Authorized Signatory", 435, top + 317, { width: 100, align: "center" });
  };
  drawCopy(28, "Office Copy");
  doc.save().dash(4, { space: 4 }).moveTo(42, 399).lineTo(553, 399).strokeColor("#94a3b8").stroke().undash().restore();
  drawCopy(420, "Receiver Copy");
  finish(doc);
  return promise;
}

export async function generateSalarySlipPdf(payroll: Record<string, any>) {
  const employee = payroll.employeeId ?? {};
  const title = "SALARY SLIP";
  const doc = createDocument(`${title} ${payroll.payrollNumber}`);
  const promise = toBuffer(doc);
  header(doc, title, `Payroll No: ${payroll.payrollNumber}  |  Salary Month: ${payroll.salaryMonth}`, true);
  const y = 176;
  doc.save().roundedRect(42, y, 511, 112, 8).fill("#f8fafc").strokeColor(line).stroke().restore();
  detailLine(doc, "Employee Name", employee.name || "-", 58, y + 17, 210);
  detailLine(doc, "Employee ID", String(employee._id || "-"), 315, y + 17, 210);
  detailLine(doc, "Department", employee.department || "-", 58, y + 63, 210);
  detailLine(doc, "Designation", employee.designation || "-", 315, y + 63, 210);
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(11).text("EARNINGS & REIMBURSEMENTS", 42, 315);
  doc.save().roundedRect(42, 340, 511, 130, 7).strokeColor(line).stroke().restore();
  doc.save().rect(42, 340, 511, 30).fill(dark).restore();
  doc.fillColor("white").font("Helvetica-Bold").fontSize(8).text("PARTICULARS", 58, 351).text("AMOUNT", 420, 351, { width: 115, align: "right" });
  [["Basic Salary", payroll.basicSalary], [`Expense Reimbursement (${(payroll.expenseIds ?? []).length} entries)`, payroll.reimbursementAmount]].forEach(([label, value], index) => {
    const rowY = 386 + index * 34; doc.fillColor(dark).font("Helvetica").fontSize(9).text(String(label), 58, rowY); doc.text(money(Number(value)), 420, rowY, { width: 115, align: "right" });
  });
  doc.moveTo(55, 449).lineTo(540, 449).strokeColor(line).stroke();
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(10).text("NET AMOUNT PAID", 58, 456).fillColor(blue).fontSize(14).text(money(payroll.totalPaid), 390, 453, { width: 145, align: "right" });
  const payY = 500;
  detailLine(doc, "Payment Date", new Date(payroll.paymentDate).toLocaleDateString("en-IN"), 42, payY);
  detailLine(doc, "Payment Mode", String(payroll.paymentMode).toUpperCase(), 205, payY);
  detailLine(doc, "Bank / Cash Account", payroll.bankAccount || "Cash", 355, payY, 198);
  detailLine(doc, "Reference No.", payroll.referenceNo || "-", 42, payY + 50);
  detailLine(doc, "Remarks", payroll.remarks || "-", 205, payY + 50, 348);
  doc.fillColor(muted).font("Helvetica-Oblique").fontSize(8).text("This is a system-generated salary slip for the salary period shown above.", 42, 625, { width: 350 });
  doc.moveTo(378, 670).lineTo(540, 670).strokeColor(dark).stroke();
  doc.fillColor(dark).font("Helvetica-Bold").fontSize(9).text("Authorized Signatory", 378, 678, { width: 162, align: "center" });
  finish(doc);
  return promise;
}
